const expertOpinionsData = [
  {
    label: "x1-c1",
    alternative: "x1",
    criteria: "c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x1-c2",
    alternative: "x1",
    criteria: "c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x1-c3",
    alternative: "x1",
    criteria: "c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x1-c4",
    alternative: "x1",
    criteria: "c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x2-c1",
    alternative: "x2",
    criteria: "c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x2-c2",
    alternative: "x2",
    criteria: "c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x2-c3",
    alternative: "x2",
    criteria: "c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x2-c4",
    alternative: "x2",
    criteria: "c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },

  {
    label: "x3-c1",
    alternative: "x3",
    criteria: "c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x3-c2",
    alternative: "x3",
    criteria: "c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x3-c3",
    alternative: "x3",
    criteria: "c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
  {
    label: "x3-c4",
    alternative: "x3",
    criteria: "c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperations: [],
  },
];
export default expertOpinionsData;
