const expertOpinionsData = [
  {
    label: "x1-c1",
    alternative: "x1",
    criteria: "c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c2",
    alternative: "x1",
    criteria: "c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c3",
    alternative: "x1",
    criteria: "c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c4",
    alternative: "x1",
    criteria: "c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c5",
    alternative: "x1",
    criteria: "c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c6",
    alternative: "x1",
    criteria: "c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c7",
    alternative: "x1",
    criteria: "c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c8",
    alternative: "x1",
    criteria: "c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c1",
    alternative: "x2",
    criteria: "c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c2",
    alternative: "x2",
    criteria: "c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c3",
    alternative: "x2",
    criteria: "c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c4",
    alternative: "x2",
    criteria: "c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c5",
    alternative: "x2",
    criteria: "c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c6",
    alternative: "x2",
    criteria: "c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c7",
    alternative: "x2",
    criteria: "c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c8",
    alternative: "x2",
    criteria: "c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c1",
    alternative: "x3",
    criteria: "c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c2",
    alternative: "x3",
    criteria: "c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c3",
    alternative: "x3",
    criteria: "c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c4",
    alternative: "x3",
    criteria: "c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c5",
    alternative: "x3",
    criteria: "c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c6",
    alternative: "x3",
    criteria: "c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c7",
    alternative: "x3",
    criteria: "c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c8",
    alternative: "x3",
    criteria: "c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c1",
    alternative: "x4",
    criteria: "c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c2",
    alternative: "x4",
    criteria: "c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c3",
    alternative: "x4",
    criteria: "c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c4",
    alternative: "x3",
    criteria: "c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c5",
    alternative: "x4",
    criteria: "c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c6",
    alternative: "x4",
    criteria: "c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c7",
    alternative: "x4",
    criteria: "c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c8",
    alternative: "x4",
    criteria: "c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
];
export default expertOpinionsData;
