const expertOpinionsData = [
  {
    label: "x1-c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x1-c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x2-c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x3-c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c1",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c2",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c3",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c4",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c5",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c6",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c7",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
  {
    label: "x4-c8",
    selectedValues: [],
    selectedLinguisticTerms: [],
    selectedOperators: [],
  },
];
export default expertOpinionsData;
